apiVersion: v1
kind: Namespace
metadata:
  name: coverage-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coverage-demo
  namespace: coverage-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coverage-demo
  template:
    metadata:
      labels:
        app: coverage-demo
    spec:
      containers:
      - name: app
        image: localhost/coverage-http-demo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: coverage-demo
  namespace: coverage-demo
spec:
  selector:
    app: coverage-demo
  ports:
  - port: 8080
    targetPort: 8080
    name: http

