apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: go-coverage-http-e2e
spec:
  description: |
    Integration test pipeline for go-coverage-http that:
    - Deploys the instrumented Go application to OpenShift
    - Runs E2E tests
    - Uses coverport to collect, push, and upload coverage to Codecov
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      type: string
    - description: Name of the secret containing cluster access kubeconfig
      name: CLUSTER_ACCESS_SECRET
      type: string
      default: integration-pipeline-credentials
    - description: Name of the secret containing OCI registry and Codecov credentials
      name: COVERPORT_SECRET
      type: string
      default: integration-pipeline-credentials
  tasks:
    - name: test-metadata
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: test-name
          value: $(context.pipelineRun.name)
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test-metadata/0.1/test-metadata.yaml
    
    - name: deploy
      runAfter:
        - test-metadata
      taskSpec:
        results:
          - name: NAMESPACE
            description: The namespace where the app was deployed
          - name: APP_URL
            description: The base URL of the deployed service
        steps:
          - name: deploy-application
            image: quay.io/konflux-ci/tekton-integration-catalog/utils:latest
            workingDir: /workspace
            env:
              - name: JOB_SPEC
                value: $(tasks.test-metadata.results.job-spec)
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
              - name: OC_LOGIN_COMMAND
                valueFrom:
                  secretKeyRef:
                    name: integration-pipeline-credentials
                    key: oc-login-command
            script: |
              #!/bin/sh
              set -eu
              
              yum install git jq -y

              # Extract component image from SNAPSHOT
              COMPONENT_IMAGE=$(echo $SNAPSHOT | jq -r '.components[0].containerImage')
              echo "Component image: $COMPONENT_IMAGE"

              # Clone the repository
              BRANCH_NAME="$(tasks.test-metadata.results.target-repo-branch)"
              if [[ "$(tasks.test-metadata.results.test-event-type)" == "pull_request" ]]; then
                BRANCH_NAME="$(tasks.test-metadata.results.source-repo-branch)"
              fi
              git clone "$(tasks.test-metadata.results.git-url)" -b $BRANCH_NAME .

              # Login to OpenShift
              eval $OC_LOGIN_COMMAND

              # Create unique namespace for this test run
              NS="go-coverage-http-$(date +%s)"
              oc new-project $NS
              echo "Created namespace: $NS"

              # Update the deployment manifest with the component image and namespace
              sed "s|image: localhost/coverage-http-demo:test|image: $COMPONENT_IMAGE|g" k8s-deployment.yaml > k8s-deployment-updated.yaml
              sed -i "s|namespace: coverage-demo|namespace: $NS|g" k8s-deployment-updated.yaml
              
              # Convert NodePort Service to ClusterIP for OpenShift
              sed -i 's|type: NodePort|type: ClusterIP|g' k8s-deployment-updated.yaml
              sed -i '/nodePort: 30082/d' k8s-deployment-updated.yaml
              
              # Add OpenShift Route for external access
              cat >> k8s-deployment-updated.yaml << EOF
              ---
              apiVersion: route.openshift.io/v1
              kind: Route
              metadata:
                name: coverage-demo
                namespace: $NS
              spec:
                to:
                  kind: Service
                  name: coverage-demo
                port:
                  targetPort: http
                tls:
                  termination: edge
                  insecureEdgeTerminationPolicy: Redirect
              EOF
              
              echo "Updated deployment manifest:"
              cat k8s-deployment-updated.yaml
              
              # Apply the deployment
              oc apply -f k8s-deployment-updated.yaml

              # Wait for deployment to be ready
              oc wait --for=condition=Available deployment/coverage-demo -n $NS --timeout=5m
              oc wait --for=condition=ready pod -l app=coverage-demo -n $NS --timeout=5m

              # Get the route hostname
              ROUTE_HOST=$(oc get route coverage-demo -n $NS -o jsonpath='{.spec.host}')
              APP_URL="https://${ROUTE_HOST}"
              echo "Application URL: $APP_URL"

              # Verify the route is accessible
              echo "Waiting for route to be accessible..."
              for i in {1..30}; do
                if curl -k -f ${APP_URL}/health 2>/dev/null; then
                  echo "✅ Route is accessible!"
                  break
                fi
                echo "Attempt $i: Route not ready yet, retrying..."
                sleep 2
              done

              echo -n "$NS" > /tekton/results/NAMESPACE
              echo -n "$APP_URL" > /tekton/results/APP_URL

    - name: run-e2e-tests
      runAfter:
        - deploy
      taskSpec:
        volumes:
          - name: source
            emptyDir: {}
        steps:
          - name: clone-repository
            image: quay.io/konflux-ci/tekton-integration-catalog/utils:latest
            workingDir: /workspace/source
            volumeMounts:
              - name: source
                mountPath: /workspace/source
            env:
              - name: GIT_URL
                value: $(tasks.test-metadata.results.git-url)
              - name: GIT_BRANCH
                value: $(tasks.test-metadata.results.target-repo-branch)
              - name: SOURCE_BRANCH
                value: $(tasks.test-metadata.results.source-repo-branch)
              - name: EVENT_TYPE
                value: $(tasks.test-metadata.results.test-event-type)
            script: |
              #!/bin/sh
              set -eu
              
              # Determine which branch to use
              if [ "$EVENT_TYPE" = "pull_request" ]; then
                BRANCH="$SOURCE_BRANCH"
              else
                BRANCH="$GIT_BRANCH"
              fi
              
              echo "Cloning $GIT_URL branch $BRANCH"
              git clone "$GIT_URL" -b "$BRANCH" /workspace/source
              cd /workspace/source
              echo "Repository cloned successfully"
              ls -la
          
          - name: run-tests
            image: registry.access.redhat.com/ubi9/go-toolset:1.24
            computeResources:
              requests:
                memory: "2Gi"
                cpu: "1000m"
              limits:
                memory: "4Gi"
                cpu: "2000m"
            workingDir: /workspace/source
            volumeMounts:
              - name: source
                mountPath: /workspace/source
            env:
              - name: APP_NAMESPACE
                value: $(tasks.deploy.results.NAMESPACE)
              - name: APP_URL
                value: $(tasks.deploy.results.APP_URL)
              - name: COVERAGE_OUTPUT_DIR
                value: /tmp/coverage-output
              - name: PUSH_COVERAGE_ARTIFACT
                value: "false"
              - name: OC_LOGIN_COMMAND
                valueFrom:
                  secretKeyRef:
                    name: integration-pipeline-credentials
                    key: oc-login-command
            script: |
              #!/bin/bash
              set -eu
              
              # Download and install oc binary
              echo "📥 Downloading oc binary..."
              curl -sL https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/oc/latest/linux/oc.tar.gz -o /tmp/oc.tar.gz
              tar -xzf /tmp/oc.tar.gz -C /tmp
              chmod +x /tmp/oc
              export PATH=/tmp:$PATH
              
              # Verify oc is available
              oc version --client
              
              # Login to OpenShift (needed for kubectl access)
              eval $OC_LOGIN_COMMAND

              # Download Go dependencies
              go mod download

              # Create coverage output directory (already set via environment variable)
              # The go-toolset image runs as non-root and can't write to /workspace/source
              mkdir -p "$COVERAGE_OUTPUT_DIR"
              chmod 777 "$COVERAGE_OUTPUT_DIR"
              echo "✅ Coverage output directory: $COVERAGE_OUTPUT_DIR"
              
              # Run E2E tests
              # These tests exercise the deployed instrumented application
              # Coverage will be collected separately by the coverport-coverage task
              cd test
              
              echo "🧪 Running E2E tests..."
              echo "   Namespace: $APP_NAMESPACE"
              echo "   App URL: $APP_URL"
              
              # Run the tests (no coverage collection needed here)
              go test -v ./...
              
              echo "✅ E2E tests completed successfully!"

    - name: collect-and-upload-coverage
      runAfter:
        - run-e2e-tests
      params:
        - name: instrumented-images
          value: $(results.test-metadata.container-image)
        - name: cluster-access-secret-name
          value: $(params.CLUSTER_ACCESS_SECRET)
        - name: test-name
          value: e2e-tests
        - name: oci-container
          value: quay.io/psturc/coverage-artifacts:$(context.pipelineRun.name)
        - name: codecov-flags
          value: e2e-tests
        - name: credentials-secret-name
          value: $(params.COVERPORT_SECRET)
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/psturc/tekton-integration-catalog.git
          - name: revision
            value: KFLUXDP-591
          - name: pathInRepo
            value: tasks/coverport-coverage/0.1/coverport-coverage.yaml

    - name: cleanup
      runAfter:
        - collect-and-upload-coverage
      taskSpec:
        steps:
          - name: cleanup-namespace
            image: quay.io/konflux-ci/tekton-integration-catalog/utils:latest
            env:
              - name: APP_NAMESPACE
                value: $(tasks.deploy.results.NAMESPACE)
              - name: OC_LOGIN_COMMAND
                valueFrom:
                  secretKeyRef:
                    name: integration-pipeline-credentials
                    key: oc-login-command
            script: |
              #!/bin/sh
              set -eu
              
              # Login to OpenShift
              eval $OC_LOGIN_COMMAND
              
              # Delete the namespace
              echo "🗑️  Cleaning up namespace: $APP_NAMESPACE"
              oc delete namespace $APP_NAMESPACE --wait=false || true
              
              echo "✅ Cleanup initiated"

